exclude: |
  (?x)^(
    src/db/migrations/.*|
    \.venv/.*|
    \.git/.*|
    __pycache__/.*|
    \.mypy_cache/.*|
    \.ruff_cache/.*|
    dist/.*|
    build/.*|
    postgres/.*       # <- добавлено исключение
  )$

repos:
  - repo: local
    hooks:
      - id: ruff-fix
        name: ruff remove unused imports
        entry: ruff check . --select F401,I --fix
        language: system
        types: [python]
        pass_filenames: false

      - id: black
        name: black
        entry: black . --exclude 'src/db/migrations|postgres'   # <- добавлено исключение
        language: system
        types: [python]
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=1000"]
