"""empty message

Revision ID: c71f0c8f0009
Revises: 0904d2717041
Create Date: 2025-10-05 15:29:39.480773

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c71f0c8f0009"
down_revision: Union[str, Sequence[str], None] = "0904d2717041"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("visits", sa.Column("month", sa.Integer(), nullable=False))
    op.add_column("visits", sa.Column("year", sa.Integer(), nullable=False))
    op.drop_column("visits", "date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "visits", sa.Column("date", sa.DATE(), autoincrement=False, nullable=False)
    )
    op.drop_column("visits", "year")
    op.drop_column("visits", "month")
    # ### end Alembic commands ###
