"""empty message

Revision ID: e0e87595fbfd
Revises: 11e5d8865652
Create Date: 2025-10-20 16:07:09.419393

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0e87595fbfd"
down_revision: Union[str, Sequence[str], None] = "11e5d8865652"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pharmacies", "indicator", existing_type=sa.VARCHAR(length=64), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pharmacies", "indicator", existing_type=sa.VARCHAR(length=64), nullable=False
    )
    # ### end Alembic commands ###
