"""empty message

Revision ID: a912938ae357
Revises: 88b581797098
Create Date: 2025-10-25 15:27:30.423423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a912938ae357'
down_revision: Union[str, Sequence[str], None] = '88b581797098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('address', sa.String(length=128), nullable=True))
    op.add_column('companies', sa.Column('import_log_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_companies_import_log_id_import_logs'), 'companies', 'import_logs', ['import_log_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_companies_import_log_id_import_logs'), 'companies', type_='foreignkey')
    op.drop_column('companies', 'import_log_id')
    op.drop_column('companies', 'address')
    # ### end Alembic commands ###
