"""empty message

Revision ID: 57f1bb5056f5
Revises: f03e298d9e28
Create Date: 2025-11-27 18:52:45.704304

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "57f1bb5056f5"
down_revision: Union[str, Sequence[str], None] = "f03e298d9e28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("doctors", sa.Column("company_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_doctors_company_id_companies"),
        "doctors",
        "companies",
        ["company_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_doctors_company_id_companies"), "doctors", type_="foreignkey"
    )
    op.drop_column("doctors", "company_id")
    # ### end Alembic commands ###
