"""empty message

Revision ID: 0ec44e91ab72
Revises: 7265dacdb7dc
Create Date: 2025-10-26 10:38:30.010549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ec44e91ab72'
down_revision: Union[str, Sequence[str], None] = '7265dacdb7dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medical_facilities', 'name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_medical_facilities_name'), 'medical_facilities', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_medical_facilities_name'), 'medical_facilities', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('medical_facilities', 'name',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###
