"""empty message

Revision ID: f872d85f7b05
Revises: ae21cf4d5951
Create Date: 2025-10-25 16:05:12.270838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f872d85f7b05'
down_revision: Union[str, Sequence[str], None] = 'ae21cf4d5951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('import_logs', 'uploaded_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('import_logs', 'uploaded_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
