"""empty message

Revision ID: da780ac4b512
Revises: 6449ba919b86
Create Date: 2025-10-03 19:08:42.362778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da780ac4b512'
down_revision: Union[str, Sequence[str], None] = '6449ba919b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brands', 'product_group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('districts', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('product_groups', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_product_groups_company_id_companies'), 'product_groups', 'companies', ['company_id'], ['id'])
    op.alter_column('skus', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skus', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('fk_product_groups_company_id_companies'), 'product_groups', type_='foreignkey')
    op.drop_column('product_groups', 'company_id')
    op.alter_column('districts', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('brands', 'product_group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
