"""empty message

Revision ID: 2d670f3e59ec
Revises: 6625a2a94d03
Create Date: 2025-12-26 17:27:59.419179

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2d670f3e59ec"
down_revision: Union[str, Sequence[str], None] = "6625a2a94d03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client_categories", sa.Column("import_log_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_client_categories_import_log_id_import_logs"),
        "client_categories",
        "import_logs",
        ["import_log_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column("countries", sa.Column("import_log_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_countries_import_log_id_import_logs"),
        "countries",
        "import_logs",
        ["import_log_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "dosage_forms", sa.Column("import_log_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_dosage_forms_import_log_id_import_logs"),
        "dosage_forms",
        "import_logs",
        ["import_log_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column("dosages", sa.Column("import_log_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_dosages_import_log_id_import_logs"),
        "dosages",
        "import_logs",
        ["import_log_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "product_groups", sa.Column("import_log_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_product_groups_import_log_id_import_logs"),
        "product_groups",
        "import_logs",
        ["import_log_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column("segments", sa.Column("import_log_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_segments_import_log_id_import_logs"),
        "segments",
        "import_logs",
        ["import_log_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_segments_import_log_id_import_logs"), "segments", type_="foreignkey"
    )
    op.drop_column("segments", "import_log_id")
    op.drop_constraint(
        op.f("fk_product_groups_import_log_id_import_logs"),
        "product_groups",
        type_="foreignkey",
    )
    op.drop_column("product_groups", "import_log_id")
    op.drop_constraint(
        op.f("fk_dosages_import_log_id_import_logs"), "dosages", type_="foreignkey"
    )
    op.drop_column("dosages", "import_log_id")
    op.drop_constraint(
        op.f("fk_dosage_forms_import_log_id_import_logs"),
        "dosage_forms",
        type_="foreignkey",
    )
    op.drop_column("dosage_forms", "import_log_id")
    op.drop_constraint(
        op.f("fk_countries_import_log_id_import_logs"), "countries", type_="foreignkey"
    )
    op.drop_column("countries", "import_log_id")
    op.drop_constraint(
        op.f("fk_client_categories_import_log_id_import_logs"),
        "client_categories",
        type_="foreignkey",
    )
    op.drop_column("client_categories", "import_log_id")
    # ### end Alembic commands ###
