"""empty message

Revision ID: dbb31dba7982
Revises: 
Create Date: 2025-09-27 19:21:42.396656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'dbb31dba7982'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_categories',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_client_categories_name'))
    )
    op.create_table('companies',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('active_users_limit', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('contract_number', sa.String(), nullable=False),
    sa.Column('contract_end_date', sa.Date(), nullable=False),
    sa.Column('can_primary_sales', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('can_secondary_sales', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('can_tertiary_sales', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('can_visits', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('can_market_analysis', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('name', name=op.f('uq_companies_name'))
    )
    op.create_index(op.f('ix_companies_contract_number'), 'companies', ['contract_number'], unique=True)
    op.create_table('countries',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_countries')),
    sa.UniqueConstraint('name', name=op.f('uq_countries_name'))
    )
    op.create_table('distributors',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_distributors')),
    sa.UniqueConstraint('name', name=op.f('uq_distributors_name'))
    )
    op.create_table('dosage_forms',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dosage_forms'))
    )
    op.create_table('dosages',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dosages'))
    )
    op.create_table('pharmacy_networks',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pharmacy_networks'))
    )
    op.create_table('positions',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions')),
    sa.UniqueConstraint('name', name=op.f('uq_positions_name'))
    )
    op.create_table('product_groups',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_groups')),
    sa.UniqueConstraint('name', name=op.f('uq_product_groups_name'))
    )
    op.create_table('promotion_types',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotion_types')),
    sa.UniqueConstraint('name', name=op.f('uq_promotion_types_name'))
    )
    op.create_table('registration_applications',
    sa.Column('owner_name', sa.String(length=64), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registration_applications')),
    sa.UniqueConstraint('company_name', name=op.f('uq_registration_applications_company_name')),
    sa.UniqueConstraint('email', name=op.f('uq_registration_applications_email'))
    )
    op.create_table('segments',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_segments')),
    sa.UniqueConstraint('name', name=op.f('uq_segments_name'))
    )
    op.create_table('specialities',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specialities')),
    sa.UniqueConstraint('name', name=op.f('uq_specialities_name'))
    )
    op.create_table('brands',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('promotion_type_id', sa.Integer(), nullable=False),
    sa.Column('product_group_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_brands_company_id_companies')),
    sa.ForeignKeyConstraint(['product_group_id'], ['product_groups.id'], name=op.f('fk_brands_product_group_id_product_groups')),
    sa.ForeignKeyConstraint(['promotion_type_id'], ['promotion_types.id'], name=op.f('fk_brands_promotion_type_id_promotion_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands'))
    )
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=True)
    op.create_table('regions',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_regions_country_id_countries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regions'))
    )
    op.create_table('users',
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('patronymic', sa.String(length=64), nullable=True),
    sa.Column('phone_number', sa.String(length=64), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_operator', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_users_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('accesstoken',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=43), nullable=False),
    sa.Column('created_at', fastapi_users_db_sqlalchemy.generics.TIMESTAMPAware(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_accesstoken_user_id_users'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_accesstoken'))
    )
    op.create_index(op.f('ix_accesstoken_created_at'), 'accesstoken', ['created_at'], unique=False)
    op.create_table('settlements',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_settlements_region_id_regions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlements'))
    )
    op.create_table('skus',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('promotion_type_id', sa.Integer(), nullable=False),
    sa.Column('product_group_id', sa.Integer(), nullable=False),
    sa.Column('dosage_form_id', sa.Integer(), nullable=False),
    sa.Column('dosage_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_skus_brand_id_brands')),
    sa.ForeignKeyConstraint(['dosage_form_id'], ['dosage_forms.id'], name=op.f('fk_skus_dosage_form_id_dosage_forms')),
    sa.ForeignKeyConstraint(['dosage_id'], ['dosages.id'], name=op.f('fk_skus_dosage_id_dosages')),
    sa.ForeignKeyConstraint(['product_group_id'], ['product_groups.id'], name=op.f('fk_skus_product_group_id_product_groups')),
    sa.ForeignKeyConstraint(['promotion_type_id'], ['promotion_types.id'], name=op.f('fk_skus_promotion_type_id_promotion_types')),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], name=op.f('fk_skus_segment_id_segments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skus'))
    )
    op.create_table('districts',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('settlement_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_districts_region_id_regions')),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], name=op.f('fk_districts_settlement_id_settlements')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_districts'))
    )
    op.create_table('primary_sales_and_stock',
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('indicator', sa.String(length=64), nullable=False),
    sa.Column('packages', sa.Float(), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], name=op.f('fk_primary_sales_and_stock_distributor_id_distributors')),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name=op.f('fk_primary_sales_and_stock_sku_id_skus')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_primary_sales_and_stock'))
    )
    op.create_index('idx_primary_sales_distributor_year_month', 'primary_sales_and_stock', ['distributor_id', 'year', 'month'], unique=False)
    op.create_index('idx_primary_sales_sku_year', 'primary_sales_and_stock', ['sku_id', 'year'], unique=False)
    op.create_index('idx_primary_sales_year_month', 'primary_sales_and_stock', ['year', 'month'], unique=False)
    op.create_table('employees',
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('product_group_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_employees_company_id_companies')),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name=op.f('fk_employees_district_id_districts')),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_employees_position_id_positions')),
    sa.ForeignKeyConstraint(['product_group_id'], ['product_groups.id'], name=op.f('fk_employees_product_group_id_product_groups')),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_employees_region_id_regions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees'))
    )
    op.create_table('medical_facilities',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('settlement_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name=op.f('fk_medical_facilities_district_id_districts')),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], name=op.f('fk_medical_facilities_settlement_id_settlements')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_facilities')),
    sa.UniqueConstraint('name', name=op.f('uq_medical_facilities_name'))
    )
    op.create_table('doctors',
    sa.Column('fullname', sa.String(length=128), nullable=False),
    sa.Column('responsible_employee_id', sa.Integer(), nullable=False),
    sa.Column('medical_facility_id', sa.Integer(), nullable=False),
    sa.Column('speciality_id', sa.Integer(), nullable=False),
    sa.Column('client_category_id', sa.Integer(), nullable=False),
    sa.Column('product_group_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_category_id'], ['client_categories.id'], name=op.f('fk_doctors_client_category_id_client_categories')),
    sa.ForeignKeyConstraint(['medical_facility_id'], ['medical_facilities.id'], name=op.f('fk_doctors_medical_facility_id_medical_facilities')),
    sa.ForeignKeyConstraint(['product_group_id'], ['product_groups.id'], name=op.f('fk_doctors_product_group_id_product_groups')),
    sa.ForeignKeyConstraint(['responsible_employee_id'], ['employees.id'], name=op.f('fk_doctors_responsible_employee_id_employees')),
    sa.ForeignKeyConstraint(['speciality_id'], ['specialities.id'], name=op.f('fk_doctors_speciality_id_specialities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctors'))
    )
    op.create_table('pharmacies',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.Column('responsible_employee_id', sa.Integer(), nullable=False),
    sa.Column('settlement_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('medical_facility_id', sa.Integer(), nullable=True),
    sa.Column('client_category_id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_network_id', sa.Integer(), nullable=False),
    sa.Column('product_group_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_category_id'], ['client_categories.id'], name=op.f('fk_pharmacies_client_category_id_client_categories')),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], name=op.f('fk_pharmacies_distributor_id_distributors')),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name=op.f('fk_pharmacies_district_id_districts')),
    sa.ForeignKeyConstraint(['medical_facility_id'], ['medical_facilities.id'], name=op.f('fk_pharmacies_medical_facility_id_medical_facilities')),
    sa.ForeignKeyConstraint(['pharmacy_network_id'], ['pharmacy_networks.id'], name=op.f('fk_pharmacies_pharmacy_network_id_pharmacy_networks')),
    sa.ForeignKeyConstraint(['product_group_id'], ['product_groups.id'], name=op.f('fk_pharmacies_product_group_id_product_groups')),
    sa.ForeignKeyConstraint(['responsible_employee_id'], ['employees.id'], name=op.f('fk_pharmacies_responsible_employee_id_employees')),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], name=op.f('fk_pharmacies_settlement_id_settlements')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pharmacies'))
    )
    op.create_table('secondary_sales',
    sa.Column('pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('indicator', sa.String(length=64), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('packages', sa.Float(), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], name=op.f('fk_secondary_sales_pharmacy_id_pharmacies')),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name=op.f('fk_secondary_sales_sku_id_skus')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secondary_sales'))
    )
    op.create_index('idx_secondary_sales_city_year', 'secondary_sales', ['city', 'year'], unique=False)
    op.create_index('idx_secondary_sales_sku_year', 'secondary_sales', ['sku_id', 'year'], unique=False)
    op.create_index('idx_secondary_sales_year_month', 'secondary_sales', ['year', 'month'], unique=False)
    op.create_table('tertiary_sales_and_stock',
    sa.Column('pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('indicator', sa.String(length=100), nullable=False),
    sa.Column('packages', sa.Float(), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], name=op.f('fk_tertiary_sales_and_stock_pharmacy_id_pharmacies')),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], name=op.f('fk_tertiary_sales_and_stock_sku_id_skus')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tertiary_sales_and_stock'))
    )
    op.create_index('idx_tertiary_sales_city_year', 'tertiary_sales_and_stock', ['city', 'year'], unique=False)
    op.create_index('idx_tertiary_sales_sku_year', 'tertiary_sales_and_stock', ['sku_id', 'year'], unique=False)
    op.create_index('idx_tertiary_sales_year_month', 'tertiary_sales_and_stock', ['year', 'month'], unique=False)
    op.create_table('visits',
    sa.Column('product_group_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('client_type', sa.String(), nullable=False),
    sa.Column('client_category_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('medical_facility_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_category_id'], ['client_categories.id'], name=op.f('fk_visits_client_category_id_client_categories')),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_visits_doctor_id_doctors')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_visits_employee_id_employees')),
    sa.ForeignKeyConstraint(['medical_facility_id'], ['medical_facilities.id'], name=op.f('fk_visits_medical_facility_id_medical_facilities')),
    sa.ForeignKeyConstraint(['product_group_id'], ['product_groups.id'], name=op.f('fk_visits_product_group_id_product_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visits'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visits')
    op.drop_index('idx_tertiary_sales_year_month', table_name='tertiary_sales_and_stock')
    op.drop_index('idx_tertiary_sales_sku_year', table_name='tertiary_sales_and_stock')
    op.drop_index('idx_tertiary_sales_city_year', table_name='tertiary_sales_and_stock')
    op.drop_table('tertiary_sales_and_stock')
    op.drop_index('idx_secondary_sales_year_month', table_name='secondary_sales')
    op.drop_index('idx_secondary_sales_sku_year', table_name='secondary_sales')
    op.drop_index('idx_secondary_sales_city_year', table_name='secondary_sales')
    op.drop_table('secondary_sales')
    op.drop_table('pharmacies')
    op.drop_table('doctors')
    op.drop_table('medical_facilities')
    op.drop_table('employees')
    op.drop_index('idx_primary_sales_year_month', table_name='primary_sales_and_stock')
    op.drop_index('idx_primary_sales_sku_year', table_name='primary_sales_and_stock')
    op.drop_index('idx_primary_sales_distributor_year_month', table_name='primary_sales_and_stock')
    op.drop_table('primary_sales_and_stock')
    op.drop_table('districts')
    op.drop_table('skus')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_accesstoken_created_at'), table_name='accesstoken')
    op.drop_table('accesstoken')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('regions')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_table('brands')
    op.drop_table('specialities')
    op.drop_table('segments')
    op.drop_table('registration_applications')
    op.drop_table('promotion_types')
    op.drop_table('product_groups')
    op.drop_table('positions')
    op.drop_table('pharmacy_networks')
    op.drop_table('dosages')
    op.drop_table('dosage_forms')
    op.drop_table('distributors')
    op.drop_table('countries')
    op.drop_index(op.f('ix_companies_contract_number'), table_name='companies')
    op.drop_table('companies')
    op.drop_table('client_categories')
    # ### end Alembic commands ###
