"""empty message

Revision ID: 11228e82ed55
Revises: 4d4de66948ac
Create Date: 2025-10-29 15:31:34.074060

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11228e82ed55"
down_revision: Union[str, Sequence[str], None] = "4d4de66948ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_secondary_sales_city_year"), table_name="secondary_sales")
    op.drop_column("secondary_sales", "city")
    op.drop_index(
        op.f("idx_tertiary_sales_city_year"), table_name="tertiary_sales_and_stock"
    )
    op.drop_column("tertiary_sales_and_stock", "city")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tertiary_sales_and_stock",
        sa.Column("city", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    op.create_index(
        op.f("idx_tertiary_sales_city_year"),
        "tertiary_sales_and_stock",
        ["city", "year"],
        unique=False,
    )
    op.add_column(
        "secondary_sales",
        sa.Column("city", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    op.create_index(
        op.f("idx_secondary_sales_city_year"),
        "secondary_sales",
        ["city", "year"],
        unique=False,
    )
    # ### end Alembic commands ###
