"""empty message

Revision ID: 4d4de66948ac
Revises: 0ec44e91ab72
Create Date: 2025-10-29 15:14:14.742170

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4d4de66948ac"
down_revision: Union[str, Sequence[str], None] = "0ec44e91ab72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "geo_indicators",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_geo_indicators")),
    )
    op.add_column(
        "medical_facilities", sa.Column("geo_indicator_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_medical_facilities_geo_indicator_id_geo_indicators"),
        "medical_facilities",
        "geo_indicators",
        ["geo_indicator_id"],
        ["id"],
    )
    op.add_column(
        "pharmacies", sa.Column("geo_indicator_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_pharmacies_geo_indicator_id_geo_indicators"),
        "pharmacies",
        "geo_indicators",
        ["geo_indicator_id"],
        ["id"],
    )
    op.drop_column("pharmacies", "indicator")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pharmacies",
        sa.Column(
            "indicator", sa.VARCHAR(length=64), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(
        op.f("fk_pharmacies_geo_indicator_id_geo_indicators"),
        "pharmacies",
        type_="foreignkey",
    )
    op.drop_column("pharmacies", "geo_indicator_id")
    op.drop_constraint(
        op.f("fk_medical_facilities_geo_indicator_id_geo_indicators"),
        "medical_facilities",
        type_="foreignkey",
    )
    op.drop_column("medical_facilities", "geo_indicator_id")
    op.drop_table("geo_indicators")
    # ### end Alembic commands ###
