"""empty message

Revision ID: db784534e635
Revises: 1badb31aaf32
Create Date: 2025-10-19 15:41:47.709852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db784534e635'
down_revision: Union[str, Sequence[str], None] = '1badb31aaf32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pharmacies', 'settlement_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pharmacies', 'district_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pharmacies', 'client_category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint('uq_settlement_id_region', 'settlements', ['id', 'region_id'])
    op.create_foreign_key('fk_district_settlement_region', 'districts', 'settlements', ['settlement_id', 'region_id'], ['id', 'region_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_settlement_id_region', 'settlements', type_='unique')
    op.drop_constraint('fk_district_settlement_region', 'districts', type_='foreignkey')

    op.alter_column('pharmacies', 'client_category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pharmacies', 'district_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pharmacies', 'settlement_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
