"""empty message

Revision ID: f87b3e21ac6b
Revises: 1e4938041b34
Create Date: 2025-10-02 02:18:00.317063

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f87b3e21ac6b"
down_revision: Union[str, Sequence[str], None] = "1e4938041b34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_password_setup_tokens_user_id_users"),
        "password_setup_tokens",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_password_setup_tokens_user_id_users"),
        "password_setup_tokens",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_password_setup_tokens_user_id_users"),
        "password_setup_tokens",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_password_setup_tokens_user_id_users"),
        "password_setup_tokens",
        "users",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
