"""empty message

Revision ID: ae21cf4d5951
Revises: a912938ae357
Create Date: 2025-10-25 15:53:08.714428

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ae21cf4d5951"
down_revision: Union[str, Sequence[str], None] = "a912938ae357"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("positions", sa.Column("import_log_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_positions_import_log_id_import_logs"),
        "positions",
        "import_logs",
        ["import_log_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_positions_import_log_id_import_logs"), "positions", type_="foreignkey"
    )
    op.drop_column("positions", "import_log_id")
    # ### end Alembic commands ###
