"""empty message

Revision ID: 6de555083ff2
Revises: 5d6aef23b030
Create Date: 2025-10-24 13:15:13.827508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6de555083ff2'
down_revision: Union[str, Sequence[str], None] = '5d6aef23b030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctors', 'responsible_employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('doctors', 'medical_facility_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('doctors', 'product_group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('employees', 'district_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('medical_facilities', sa.Column('facility_type', sa.String(length=64), nullable=False))
    op.alter_column('medical_facilities', 'district_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('medical_facilities', 'address',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('pharmacies', 'distributor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('visits', sa.Column('pharmacy_id', sa.Integer(), nullable=True))
    op.alter_column('visits', 'client_category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('visits', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('visits', 'medical_facility_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(op.f('fk_visits_pharmacy_id_pharmacies'), 'visits', 'pharmacies', ['pharmacy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_visits_pharmacy_id_pharmacies'), 'visits', type_='foreignkey')
    op.alter_column('visits', 'medical_facility_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('visits', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('visits', 'client_category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('visits', 'pharmacy_id')
    op.alter_column('pharmacies', 'distributor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('medical_facilities', 'address',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('medical_facilities', 'district_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('medical_facilities', 'facility_type')
    op.alter_column('employees', 'district_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('doctors', 'product_group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('doctors', 'medical_facility_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('doctors', 'responsible_employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
