"""empty message

Revision ID: 11e5d8865652
Revises: db784534e635
Create Date: 2025-10-19 16:30:46.212523

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11e5d8865652"
down_revision: Union[str, Sequence[str], None] = "db784534e635"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_district_id_region", "districts", ["id", "region_id"]
    )
    op.create_foreign_key(
        "fk_employee_district_region",
        "employees",
        "districts",
        ["district_id", "region_id"],
        ["id", "region_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_employee_district_region", "employees", type_="foreignkey")
    op.drop_constraint("uq_district_id_region", "districts", type_="unique")
    # ### end Alembic commands ###
