"""empty message

Revision ID: 7cdfd9f10f45
Revises: 6de555083ff2
Create Date: 2025-10-24 16:07:05.882254

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7cdfd9f10f45"
down_revision: Union[str, Sequence[str], None] = "6de555083ff2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("position", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "position")
    # ### end Alembic commands ###
