"""empty message

Revision ID: 4989e5a5fc6f
Revises: f87b3e21ac6b
Create Date: 2025-10-02 19:18:35.422790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4989e5a5fc6f'
down_revision: Union[str, Sequence[str], None] = 'f87b3e21ac6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('primary_sales_and_stock', 'amount_usd', new_column_name='amount', existing_type=sa.Float(), nullable=False)
    op.alter_column('secondary_sales', 'amount_usd', new_column_name='amount', existing_type=sa.Float(), nullable=False)
    op.alter_column('tertiary_sales_and_stock', 'amount_usd', new_column_name='amount', existing_type=sa.Float(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tertiary_sales_and_stock', 'amount', new_column_name='amount_usd', existing_type=sa.Float(), nullable=False)
    op.alter_column('secondary_sales', 'amount', new_column_name='amount_usd', existing_type=sa.Float(), nullable=False)
    op.alter_column('primary_sales_and_stock', 'amount', new_column_name='amount_usd', existing_type=sa.Float(), nullable=False)
    # ### end Alembic commands ###
