"""empty message

Revision ID: 8eb7cd594cde
Revises: 11228e82ed55
Create Date: 2025-10-29 15:49:31.277506

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8eb7cd594cde"
down_revision: Union[str, Sequence[str], None] = "11228e82ed55"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "geo_indicators", sa.Column("import_log_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_geo_indicators_import_log_id_import_logs"),
        "geo_indicators",
        "import_logs",
        ["import_log_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_geo_indicators_import_log_id_import_logs"),
        "geo_indicators",
        type_="foreignkey",
    )
    op.drop_column("geo_indicators", "import_log_id")
    # ### end Alembic commands ###
