"""empty message

Revision ID: 1badb31aaf32
Revises: 20ed6e8d0579
Create Date: 2025-10-18 16:50:04.411827

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1badb31aaf32"
down_revision: Union[str, Sequence[str], None] = "20ed6e8d0579"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ims",
        sa.Column("company", sa.String(), nullable=False),
        sa.Column("brand", sa.String(), nullable=False),
        sa.Column("segment", sa.String(), nullable=False),
        sa.Column("dosage", sa.String(), nullable=False),
        sa.Column("dosage_form", sa.String(), nullable=False),
        sa.Column("period", sa.String(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("packages", sa.Float(), nullable=False),
        sa.Column("molecule", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ims")),
    )
    op.alter_column(
        "districts", "settlement_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "districts", "settlement_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_table("ims")
    # ### end Alembic commands ###
