"""empty message

Revision ID: 5d6aef23b030
Revises: 9d7103e3227f
Create Date: 2025-10-22 17:52:38.882238

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d6aef23b030"
down_revision: Union[str, Sequence[str], None] = "9d7103e3227f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("brands", sa.Column("ims_name", sa.String(length=64), nullable=True))
    op.create_unique_constraint(op.f("uq_brands_ims_name"), "brands", ["ims_name"])
    op.alter_column("companies", "ims_name", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("companies", "ims_name", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_constraint(op.f("uq_brands_ims_name"), "brands", type_="unique")
    op.drop_column("brands", "ims_name")
    # ### end Alembic commands ###
