"""empty message

Revision ID: dda2ce01f949
Revises: 760f3fb8c969
Create Date: 2025-10-03 17:27:45.950611

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dda2ce01f949"
down_revision: Union[str, Sequence[str], None] = "760f3fb8c969"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pharmacies", sa.Column("company_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        op.f("fk_pharmacies_company_id_companies"),
        "pharmacies",
        "companies",
        ["company_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_pharmacies_company_id_companies"), "pharmacies", type_="foreignkey"
    )
    op.drop_column("pharmacies", "company_id")
    # ### end Alembic commands ###
