"""empty message

Revision ID: 7265dacdb7dc
Revises: c50f59e8c89e
Create Date: 2025-10-26 10:35:55.725124

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7265dacdb7dc"
down_revision: Union[str, Sequence[str], None] = "c50f59e8c89e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "medical_facilities",
        "facility_type",
        existing_type=sa.VARCHAR(length=64),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "medical_facilities",
        "facility_type",
        existing_type=sa.VARCHAR(length=64),
        nullable=False,
    )
    # ### end Alembic commands ###
