"""empty message

Revision ID: c50f59e8c89e
Revises: a35a39d40a7b
Create Date: 2025-10-25 21:39:50.864312

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c50f59e8c89e"
down_revision: Union[str, Sequence[str], None] = "a35a39d40a7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_visits_client_category_id_client_categories"),
        "visits",
        type_="foreignkey",
    )
    op.drop_column("visits", "client_category_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "visits",
        sa.Column(
            "client_category_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        op.f("fk_visits_client_category_id_client_categories"),
        "visits",
        "client_categories",
        ["client_category_id"],
        ["id"],
    )
    # ### end Alembic commands ###
