"""empty message

Revision ID: e0de1a5aa17c
Revises: 2d670f3e59ec
Create Date: 2025-12-28 15:28:32.271658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0de1a5aa17c'
down_revision: Union[str, Sequence[str], None] = '2d670f3e59ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skus', 'dosage_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('skus', 'segment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skus', 'segment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('skus', 'dosage_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
