"""empty message

Revision ID: 20ed6e8d0579
Revises: 4dad3681af12
Create Date: 2025-10-18 05:33:30.591148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20ed6e8d0579'
down_revision: Union[str, Sequence[str], None] = '4dad3681af12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_logs',
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('target_table', sa.String(), nullable=False),
    sa.Column('records_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_import_logs_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_logs'))
    )
    op.add_column('brands', sa.Column('import_log_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_brands_import_log_id_import_logs'), 'brands', 'import_logs', ['import_log_id'], ['id'], ondelete='CASCADE')
    op.add_column('distributors', sa.Column('import_log_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_distributors_import_log_id_import_logs'), 'distributors', 'import_logs', ['import_log_id'], ['id'], ondelete='CASCADE')
    op.add_column('districts', sa.Column('import_log_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_districts_import_log_id_import_logs'), 'districts', 'import_logs', ['import_log_id'], ['id'], ondelete='CASCADE')
    op.add_column('doctors', sa.Column('import_log_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_doctors_import_log_id_import_logs'), 'doctors', 'import_logs', ['import_log_id'], ['id'], ondelete='CASCADE')
    op.add_column('employees', sa.Column('import_log_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_employees_import_log_id_import_logs'), 'employees', 'import_logs', ['import_log_id'], ['id'], ondelete='CASCADE')
    op.add_column('medical_facilities', sa.Column('import_log_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_medical_facilities_import_log_id_import_logs'), 'medical_facilities', 'import_logs', ['import_log_id'], ['id'], ondelete='CASCADE')
    op.add_column('pharmacies', sa.Column('import_log_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_pharmacies_import_log_id_import_logs'), 'pharmacies', 'import_logs', ['import_log_id'], ['id'], ondelete='CASCADE')
    op.add_column('primary_sales_and_stock', sa.Column('import_log_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_primary_sales_and_stock_import_log_id_import_logs'), 'primary_sales_and_stock', 'import_logs', ['import_log_id'], ['id'], ondelete='CASCADE')
    op.add_column('regions', sa.Column('import_log_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_regions_import_log_id_import_logs'), 'regions', 'import_logs', ['import_log_id'], ['id'], ondelete='CASCADE')
    op.add_column('secondary_sales', sa.Column('import_log_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_secondary_sales_import_log_id_import_logs'), 'secondary_sales', 'import_logs', ['import_log_id'], ['id'], ondelete='CASCADE')
    op.add_column('settlements', sa.Column('import_log_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_settlements_import_log_id_import_logs'), 'settlements', 'import_logs', ['import_log_id'], ['id'], ondelete='CASCADE')
    op.add_column('skus', sa.Column('import_log_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_skus_import_log_id_import_logs'), 'skus', 'import_logs', ['import_log_id'], ['id'], ondelete='CASCADE')
    op.add_column('specialities', sa.Column('import_log_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_specialities_import_log_id_import_logs'), 'specialities', 'import_logs', ['import_log_id'], ['id'], ondelete='CASCADE')
    op.add_column('tertiary_sales_and_stock', sa.Column('import_log_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_tertiary_sales_and_stock_import_log_id_import_logs'), 'tertiary_sales_and_stock', 'import_logs', ['import_log_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tertiary_sales_and_stock_import_log_id_import_logs'), 'tertiary_sales_and_stock', type_='foreignkey')
    op.drop_column('tertiary_sales_and_stock', 'import_log_id')
    op.drop_constraint(op.f('fk_specialities_import_log_id_import_logs'), 'specialities', type_='foreignkey')
    op.drop_column('specialities', 'import_log_id')
    op.drop_constraint(op.f('fk_skus_import_log_id_import_logs'), 'skus', type_='foreignkey')
    op.drop_column('skus', 'import_log_id')
    op.drop_constraint(op.f('fk_settlements_import_log_id_import_logs'), 'settlements', type_='foreignkey')
    op.drop_column('settlements', 'import_log_id')
    op.drop_constraint(op.f('fk_secondary_sales_import_log_id_import_logs'), 'secondary_sales', type_='foreignkey')
    op.drop_column('secondary_sales', 'import_log_id')
    op.drop_constraint(op.f('fk_regions_import_log_id_import_logs'), 'regions', type_='foreignkey')
    op.drop_column('regions', 'import_log_id')
    op.drop_constraint(op.f('fk_primary_sales_and_stock_import_log_id_import_logs'), 'primary_sales_and_stock', type_='foreignkey')
    op.drop_column('primary_sales_and_stock', 'import_log_id')
    op.drop_constraint(op.f('fk_pharmacies_import_log_id_import_logs'), 'pharmacies', type_='foreignkey')
    op.drop_column('pharmacies', 'import_log_id')
    op.drop_constraint(op.f('fk_medical_facilities_import_log_id_import_logs'), 'medical_facilities', type_='foreignkey')
    op.drop_column('medical_facilities', 'import_log_id')
    op.drop_constraint(op.f('fk_employees_import_log_id_import_logs'), 'employees', type_='foreignkey')
    op.drop_column('employees', 'import_log_id')
    op.drop_constraint(op.f('fk_doctors_import_log_id_import_logs'), 'doctors', type_='foreignkey')
    op.drop_column('doctors', 'import_log_id')
    op.drop_constraint(op.f('fk_districts_import_log_id_import_logs'), 'districts', type_='foreignkey')
    op.drop_column('districts', 'import_log_id')
    op.drop_constraint(op.f('fk_distributors_import_log_id_import_logs'), 'distributors', type_='foreignkey')
    op.drop_column('distributors', 'import_log_id')
    op.drop_constraint(op.f('fk_brands_import_log_id_import_logs'), 'brands', type_='foreignkey')
    op.drop_column('brands', 'import_log_id')
    op.drop_table('import_logs')
    # ### end Alembic commands ###
