"""empty message

Revision ID: 4dad3681af12
Revises: 284745447952
Create Date: 2025-10-14 17:40:27.042407

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4dad3681af12"
down_revision: Union[str, Sequence[str], None] = "284745447952"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("companies", sa.Column("ims_name", sa.String(), nullable=True))
    op.execute(
        "UPDATE companies SET ims_name = 'company_' || id::text WHERE ims_name IS NULL"
    )
    op.alter_column("companies", "ims_name", nullable=False)
    op.create_unique_constraint(
        op.f("uq_companies_ims_name"), "companies", ["ims_name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_companies_ims_name"), "companies", type_="unique")
    op.drop_column("companies", "ims_name")
    # ### end Alembic commands ###
