"""empty message

Revision ID: 9d7103e3227f
Revises: 4881d1a5ba99
Create Date: 2025-10-22 14:54:30.339817

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d7103e3227f"
down_revision: Union[str, Sequence[str], None] = "4881d1a5ba99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_employee_district_region"), "employees", type_="foreignkey"
    )
    op.drop_constraint(op.f("uq_district_id_region"), "districts", type_="unique")
    op.create_unique_constraint(
        "uq_district_name_region", "districts", ["name", "region_id"]
    )
    op.drop_constraint(
        op.f("fk_district_settlement_region"), "districts", type_="foreignkey"
    )
    op.create_unique_constraint(
        "uq_region_name_country", "regions", ["name", "country_id"]
    )
    op.drop_constraint(op.f("uq_settlement_id_region"), "settlements", type_="unique")
    op.create_unique_constraint(
        "uq_settlement_name_region", "settlements", ["name", "region_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_settlement_name_region", "settlements", type_="unique")
    op.create_unique_constraint(
        op.f("uq_settlement_id_region"),
        "settlements",
        ["id", "region_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint("uq_region_name_country", "regions", type_="unique")
    op.create_unique_constraint(
        op.f("uq_district_id_region"),
        "districts",
        ["id", "region_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_foreign_key(
        op.f("fk_employee_district_region"),
        "employees",
        "districts",
        ["district_id", "region_id"],
        ["id", "region_id"],
    )
    op.create_foreign_key(
        op.f("fk_district_settlement_region"),
        "districts",
        "settlements",
        ["settlement_id", "region_id"],
        ["id", "region_id"],
    )
    op.drop_constraint("uq_district_name_region", "districts", type_="unique")
    # ### end Alembic commands ###
