"""empty message

Revision ID: a35a39d40a7b
Revises: f872d85f7b05
Create Date: 2025-10-25 18:19:29.422880

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a35a39d40a7b"
down_revision: Union[str, Sequence[str], None] = "f872d85f7b05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_region_name_country"), "regions", type_="unique")
    op.create_unique_constraint(op.f("uq_regions_name"), "regions", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_regions_name"), "regions", type_="unique")
    op.create_unique_constraint(
        op.f("uq_region_name_country"),
        "regions",
        ["name", "country_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
