"""empty message

Revision ID: 0904d2717041
Revises: da780ac4b512
Create Date: 2025-10-05 11:11:53.793053

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0904d2717041"
down_revision: Union[str, Sequence[str], None] = "da780ac4b512"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_pharmacies_pharmacy_network_id_pharmacy_networks"),
        "pharmacies",
        type_="foreignkey",
    )
    op.drop_column("pharmacies", "pharmacy_network_id")
    op.drop_table("pharmacy_networks")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pharmacies",
        sa.Column(
            "pharmacy_network_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        op.f("fk_pharmacies_pharmacy_network_id_pharmacy_networks"),
        "pharmacies",
        "pharmacy_networks",
        ["pharmacy_network_id"],
        ["id"],
    )
    op.create_table(
        "pharmacy_networks",
        sa.Column("name", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pharmacy_networks")),
    )
    # ### end Alembic commands ###
