"""empty message

Revision ID: 760f3fb8c969
Revises: 4989e5a5fc6f
Create Date: 2025-10-03 17:21:46.793266

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "760f3fb8c969"
down_revision: Union[str, Sequence[str], None] = "4989e5a5fc6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "doctors",
        "fullname",
        new_column_name="full_name",
        existing_type=sa.String(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "doctors",
        "full_name",
        new_column_name="fullname",
        existing_type=sa.String(),
        nullable=False,
    )
    # ### end Alembic commands ###
