"""empty message

Revision ID: 284745447952
Revises: c71f0c8f0009
Create Date: 2025-10-14 12:18:30.261623

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "284745447952"
down_revision: Union[str, Sequence[str], None] = "c71f0c8f0009"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("""
        UPDATE users
        SET first_name = ''
        WHERE first_name IS NULL
    """)

    op.execute("""
        UPDATE users
        SET last_name = ''
        WHERE last_name IS NULL
    """)

    op.alter_column(
        "users", "first_name", existing_type=sa.VARCHAR(length=64), nullable=False
    )
    op.alter_column(
        "users", "last_name", existing_type=sa.VARCHAR(length=64), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "last_name", existing_type=sa.VARCHAR(length=64), nullable=True
    )
    op.alter_column(
        "users", "first_name", existing_type=sa.VARCHAR(length=64), nullable=True
    )
    # ### end Alembic commands ###
