"""empty message

Revision ID: 1e4938041b34
Revises: dbb31dba7982
Create Date: 2025-09-30 19:06:51.056144

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1e4938041b34"
down_revision: Union[str, Sequence[str], None] = "dbb31dba7982"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "password_setup_tokens",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("is_used", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_password_setup_tokens_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_password_setup_tokens")),
    )
    op.create_index(
        op.f("ix_password_setup_tokens_token"),
        "password_setup_tokens",
        ["token"],
        unique=True,
    )
    op.alter_column(
        "brands", "product_group_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.add_column(
        "pharmacies", sa.Column("indicator", sa.String(length=64), nullable=False)
    )
    op.drop_constraint(
        op.f("fk_pharmacies_medical_facility_id_medical_facilities"),
        "pharmacies",
        type_="foreignkey",
    )
    op.drop_column("pharmacies", "medical_facility_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pharmacies",
        sa.Column(
            "medical_facility_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        op.f("fk_pharmacies_medical_facility_id_medical_facilities"),
        "pharmacies",
        "medical_facilities",
        ["medical_facility_id"],
        ["id"],
    )
    op.drop_column("pharmacies", "indicator")
    op.alter_column(
        "brands", "product_group_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_index(
        op.f("ix_password_setup_tokens_token"), table_name="password_setup_tokens"
    )
    op.drop_table("password_setup_tokens")
    # ### end Alembic commands ###
