"""empty message

Revision ID: 6449ba919b86
Revises: dda2ce01f949
Create Date: 2025-10-03 17:50:58.084455

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6449ba919b86"
down_revision: Union[str, Sequence[str], None] = "dda2ce01f949"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("districts", sa.Column("company_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_districts_company_id_companies"),
        "districts",
        "companies",
        ["company_id"],
        ["id"],
    )
    op.add_column("skus", sa.Column("company_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_skus_company_id_companies"),
        "skus",
        "companies",
        ["company_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_skus_company_id_companies"), "skus", type_="foreignkey")
    op.drop_column("skus", "company_id")
    op.drop_constraint(
        op.f("fk_districts_company_id_companies"), "districts", type_="foreignkey"
    )
    op.drop_column("districts", "company_id")
    # ### end Alembic commands ###
