"""add import_log_id to visits ims

Revision ID: bbb403440432
Revises: 0a8370adcc8f
Create Date: 2026-02-18 21:26:46.511074

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bbb403440432"
down_revision: Union[str, Sequence[str], None] = "0a8370adcc8f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ims", sa.Column("import_log_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_ims_import_log_id_import_logs"),
        "ims",
        "import_logs",
        ["import_log_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column("visits", sa.Column("import_log_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_visits_import_log_id_import_logs"),
        "visits",
        "import_logs",
        ["import_log_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_visits_import_log_id_import_logs"), "visits", type_="foreignkey"
    )
    op.drop_column("visits", "import_log_id")
    op.drop_constraint(
        op.f("fk_ims_import_log_id_import_logs"), "ims", type_="foreignkey"
    )
    op.drop_column("ims", "import_log_id")
    # ### end Alembic commands ###
