"""empty message

Revision ID: ef81df17a52b
Revises: 30e6bfab72e4
Create Date: 2026-04-02 21:07:58.773469

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ef81df17a52b'
down_revision: Union[str, Sequence[str], None] = '30e6bfab72e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_import_logs_created_at'), table_name='import_logs')
    op.create_index('idx_import_logs_created_at', 'import_logs', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_tertiary_sales_covering_report', 'tertiary_sales_and_stock', ['indicator', 'year', 'month', 'sku_id', 'pharmacy_id', 'distributor_id'], unique=False, postgresql_include=['packages', 'amount'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tertiary_sales_covering_report', table_name='tertiary_sales_and_stock', postgresql_include=['packages', 'amount'])
    op.drop_index('idx_import_logs_created_at', table_name='import_logs', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_import_logs_created_at'), 'import_logs', [sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###
