"""add_uq_facility_name_settlement

Revision ID: 622bd0cc905a
Revises: e3b35d465c4e
Create Date: 2026-02-17 09:26:59.749896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '622bd0cc905a'
down_revision: Union[str, Sequence[str], None] = 'e3b35d465c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_facility_name_settlement', 'medical_facilities', ['name', 'settlement_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_facility_name_settlement', 'medical_facilities', type_='unique')
    # ### end Alembic commands ###
