"""add indexes

Revision ID: 831beec72a68
Revises: 3f1a9d2b7c41
Create Date: 2026-02-07 12:09:31.850084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '831beec72a68'
down_revision: Union[str, Sequence[str], None] = '3f1a9d2b7c41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_distributor_name', 'distributors', ['name'], unique=False)
    op.create_index('idx_doctor_medical_facility', 'doctors', ['medical_facility_id'], unique=False)
    op.create_index('idx_doctor_speciality', 'doctors', ['speciality_id'], unique=False)
    op.create_index('idx_employee_company', 'employees', ['company_id'], unique=False)
    op.create_index('idx_employee_product_group', 'employees', ['product_group_id'], unique=False)
    op.create_index('idx_ims_brand', 'ims', ['brand'], unique=False)
    op.create_index('idx_ims_company', 'ims', ['company'], unique=False)
    op.create_index('idx_ims_dosage_form', 'ims', ['dosage_form'], unique=False)
    op.create_index('idx_ims_molecule', 'ims', ['molecule'], unique=False)
    op.create_index('idx_ims_period', 'ims', ['period'], unique=False)
    op.create_index('idx_ims_segment', 'ims', ['segment'], unique=False)
    op.create_index('idx_med_facility_geo_indicator', 'medical_facilities', ['geo_indicator_id'], unique=False)
    op.create_index('idx_pharmacy_company', 'pharmacies', ['company_id'], unique=False)
    op.create_index('idx_pharmacy_distributor', 'pharmacies', ['distributor_id'], unique=False)
    op.create_index('idx_pharmacy_geo_indicator', 'pharmacies', ['geo_indicator_id'], unique=False)
    op.create_index('idx_primary_sales_filters', 'primary_sales_and_stock', ['distributor_id', 'sku_id', 'year', 'quarter', 'month', 'indicator', 'published'], unique=False)
    op.create_index('idx_secondary_sales_filters', 'secondary_sales', ['pharmacy_id', 'sku_id', 'year', 'quarter', 'month', 'indicator', 'published'], unique=False)
    op.create_index('idx_sku_brand', 'skus', ['brand_id'], unique=False)
    op.create_index('idx_sku_company', 'skus', ['company_id'], unique=False)
    op.create_index('idx_sku_product_group', 'skus', ['product_group_id'], unique=False)
    op.create_index('idx_sku_promotion', 'skus', ['promotion_type_id'], unique=False)
    op.create_index('idx_sku_segment', 'skus', ['segment_id'], unique=False)
    op.create_index('idx_tertiary_sales_filters', 'tertiary_sales_and_stock', ['pharmacy_id', 'sku_id', 'year', 'quarter', 'month', 'indicator', 'published'], unique=False)
    op.create_index('idx_visits_filters', 'visits', ['year', 'month', 'employee_id', 'pharmacy_id', 'medical_facility_id', 'product_group_id', 'doctor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_visits_filters', table_name='visits')
    op.drop_index('idx_tertiary_sales_filters', table_name='tertiary_sales_and_stock')
    op.drop_index('idx_sku_segment', table_name='skus')
    op.drop_index('idx_sku_promotion', table_name='skus')
    op.drop_index('idx_sku_product_group', table_name='skus')
    op.drop_index('idx_sku_company', table_name='skus')
    op.drop_index('idx_sku_brand', table_name='skus')
    op.drop_index('idx_secondary_sales_filters', table_name='secondary_sales')
    op.drop_index('idx_primary_sales_filters', table_name='primary_sales_and_stock')
    op.drop_index('idx_pharmacy_geo_indicator', table_name='pharmacies')
    op.drop_index('idx_pharmacy_distributor', table_name='pharmacies')
    op.drop_index('idx_pharmacy_company', table_name='pharmacies')
    op.drop_index('idx_med_facility_geo_indicator', table_name='medical_facilities')
    op.drop_index('idx_ims_segment', table_name='ims')
    op.drop_index('idx_ims_period', table_name='ims')
    op.drop_index('idx_ims_molecule', table_name='ims')
    op.drop_index('idx_ims_dosage_form', table_name='ims')
    op.drop_index('idx_ims_company', table_name='ims')
    op.drop_index('idx_ims_brand', table_name='ims')
    op.drop_index('idx_employee_product_group', table_name='employees')
    op.drop_index('idx_employee_company', table_name='employees')
    op.drop_index('idx_doctor_speciality', table_name='doctors')
    op.drop_index('idx_doctor_medical_facility', table_name='doctors')
    op.drop_index('idx_distributor_name', table_name='distributors')
    # ### end Alembic commands ###
