"""refactor doctor to global_doctor relation

Revision ID: 48726098a1de
Revises: c7a1f3b6d9e4
Create Date: 2026-04-01 15:48:08.954026

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48726098a1de"
down_revision: Union[str, Sequence[str], None] = "c7a1f3b6d9e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_doctor_full_name"), table_name="doctors")
    op.drop_index(op.f("idx_doctor_medical_facility"), table_name="doctors")
    op.drop_index(op.f("idx_doctor_speciality"), table_name="doctors")
    op.execute(
        "ALTER TABLE doctors DROP CONSTRAINT IF EXISTS uq_doctor_full_name_medical_facility_speciality_company"
    )

    # Create global_doctors table
    op.create_table(
        "global_doctors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=256), nullable=False),
        sa.Column("medical_facility_id", sa.Integer(), nullable=False),
        sa.Column("speciality_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["medical_facility_id"],
            ["medical_facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["speciality_id"],
            ["specialities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "full_name",
            "medical_facility_id",
            "speciality_id",
            name="uq_global_doctor_unique",
        ),
    )
    op.create_index(
        "idx_global_doctor_full_name", "global_doctors", ["full_name"], unique=False
    )

    # Populate global_doctors from existing doctors
    op.execute(
        """
        INSERT INTO global_doctors (full_name, medical_facility_id, speciality_id, created_at, updated_at)
        SELECT DISTINCT full_name, medical_facility_id, speciality_id, NOW(), NOW()
        FROM doctors
        """
    )

    # Add global_doctor_id column to doctors
    op.add_column("doctors", sa.Column("global_doctor_id", sa.Integer(), nullable=True))

    # Populate global_doctor_id
    op.execute(
        """
        UPDATE doctors d
        SET global_doctor_id = gd.id
        FROM global_doctors gd
        WHERE gd.full_name = d.full_name
          AND gd.medical_facility_id = d.medical_facility_id
          AND gd.speciality_id = d.speciality_id
        """
    )

    # Create indexes and constraints
    op.create_foreign_key(
        "fk_doctors_global_doctor_id",
        "doctors",
        "global_doctors",
        ["global_doctor_id"],
        ["id"],
    )
    op.create_index("idx_doctor_global", "doctors", ["global_doctor_id"], unique=False)
    op.create_unique_constraint(
        "uq_doctor_global_company", "doctors", ["global_doctor_id", "company_id"]
    )
    op.drop_constraint(
        op.f("fk_doctors_speciality_id_specialities"), "doctors", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_doctors_medical_facility_id_medical_facilities"),
        "doctors",
        type_="foreignkey",
    )
    op.drop_column("doctors", "medical_facility_id")
    op.drop_column("doctors", "full_name")
    op.drop_column("doctors", "speciality_id")
    op.alter_column("doctors", "global_doctor_id", nullable=False)
    op.drop_index(op.f("idx_import_logs_created_at"), table_name="import_logs")
    op.create_index(
        "idx_import_logs_created_at",
        "import_logs",
        ["created_at"],
        unique=False,
        postgresql_ops={"created_at": "DESC"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_import_logs_created_at",
        table_name="import_logs",
        postgresql_ops={"created_at": "DESC"},
    )
    op.create_index(
        op.f("idx_import_logs_created_at"),
        "import_logs",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.add_column(
        "doctors",
        sa.Column("speciality_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "doctors",
        sa.Column(
            "full_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "doctors",
        sa.Column(
            "medical_facility_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        op.f("fk_doctors_medical_facility_id_medical_facilities"),
        "doctors",
        "medical_facilities",
        ["medical_facility_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_doctors_speciality_id_specialities"),
        "doctors",
        "specialities",
        ["speciality_id"],
        ["id"],
    )
    op.drop_constraint("uq_doctor_global_company", "doctors", type_="unique")
    op.drop_index("idx_doctor_global", table_name="doctors")
    op.drop_constraint("fk_doctors_global_doctor_id", "doctors", type_="foreignkey")
    op.drop_column("doctors", "global_doctor_id")
    op.drop_table("global_doctors")
    # ### end Alembic commands ###
