"""empty message

Revision ID: 62d54bbf69de
Revises: 27d85506e8a6
Create Date: 2026-03-13 03:41:56.801763

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '62d54bbf69de'
down_revision: Union[str, Sequence[str], None] = '27d85506e8a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotion_types', sa.Column('import_log_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_promotion_types_import_log_id_import_logs'), 'promotion_types', 'import_logs', ['import_log_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_promotion_types_import_log_id_import_logs'), 'promotion_types', type_='foreignkey')
    op.drop_column('promotion_types', 'import_log_id')
    # ### end Alembic commands ###
