"""add_company_relationship_to_doctor

Revision ID: 27d85506e8a6
Revises: 708ef90a4527
Create Date: 2026-03-12 17:50:48.375367

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '27d85506e8a6'
down_revision: Union[str, Sequence[str], None] = '708ef90a4527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_brand_company', 'brands', ['company_id'], unique=False)
    op.create_index('idx_brand_ims_name', 'brands', ['ims_name'], unique=False)
    op.create_index('idx_brand_name', 'brands', ['name'], unique=False)
    op.create_index('idx_client_category_name', 'client_categories', ['name'], unique=False)
    op.create_index('idx_companny_ims_name', 'companies', ['ims_name'], unique=False)
    op.create_index('idx_company_name', 'companies', ['name'], unique=False)
    op.create_index('idx_country_name', 'countries', ['name'], unique=False)
    op.create_index('idx_district_name', 'districts', ['name'], unique=False)
    op.create_index('idx_doctor_company', 'doctors', ['company_id'], unique=False)
    op.create_index('idx_doctor_full_name', 'doctors', ['full_name'], unique=False)
    op.create_index('idx_dosage_form_name', 'dosage_forms', ['name'], unique=False)
    op.create_index('idx_dosage_name', 'dosages', ['name'], unique=False)
    op.create_index('idx_employee_full_name', 'employees', ['full_name'], unique=False)
    op.create_index('idx_geo_indicator_name', 'geo_indicators', ['name'], unique=False)
    op.create_index('idx_medical_facility_name', 'medical_facilities', ['name'], unique=False)
    op.create_index('idx_pharmacy_name', 'pharmacies', ['name'], unique=False)
    op.create_index('idx_pharmacy_name_product_group', 'pharmacies', ['name', 'product_group_id'], unique=False)
    op.create_index('idx_position_name', 'positions', ['name'], unique=False)
    op.create_index('idx_primary_sales_pharmacy_sku_month_year', 'primary_sales_and_stock', ['distributor_id', 'sku_id', 'month', 'year'], unique=False)
    op.create_index('idx_product_group_company', 'product_groups', ['company_id'], unique=False)
    op.create_index('idx_product_group_name', 'product_groups', ['name'], unique=False)
    op.create_index('idx_promotion_type_name', 'promotion_types', ['name'], unique=False)
    op.create_index('idx_region_name', 'regions', ['name'], unique=False)
    op.create_index('idx_secondary_sales_pharmacy_sku_month_year', 'secondary_sales', ['pharmacy_id', 'sku_id', 'month', 'year'], unique=False)
    op.create_index('idx_segment_name', 'segments', ['name'], unique=False)
    op.create_index('idx_settlement_name', 'settlements', ['name'], unique=False)
    op.create_index('idx_sku_name', 'skus', ['name'], unique=False)
    op.create_index('idx_sku_name_company', 'skus', ['name', 'company_id'], unique=False)
    op.create_index('idx_speciality_name', 'specialities', ['name'], unique=False)
    op.create_index('idx_tertiary_sales_pharmacy_sku_month_year', 'tertiary_sales_and_stock', ['pharmacy_id', 'sku_id', 'month', 'year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tertiary_sales_pharmacy_sku_month_year', table_name='tertiary_sales_and_stock')
    op.drop_index('idx_speciality_name', table_name='specialities')
    op.drop_index('idx_sku_name_company', table_name='skus')
    op.drop_index('idx_sku_name', table_name='skus')
    op.drop_index('idx_settlement_name', table_name='settlements')
    op.drop_index('idx_segment_name', table_name='segments')
    op.drop_index('idx_secondary_sales_pharmacy_sku_month_year', table_name='secondary_sales')
    op.drop_index('idx_region_name', table_name='regions')
    op.drop_index('idx_promotion_type_name', table_name='promotion_types')
    op.drop_index('idx_product_group_name', table_name='product_groups')
    op.drop_index('idx_product_group_company', table_name='product_groups')
    op.drop_index('idx_primary_sales_pharmacy_sku_month_year', table_name='primary_sales_and_stock')
    op.drop_index('idx_position_name', table_name='positions')
    op.drop_index('idx_pharmacy_name_product_group', table_name='pharmacies')
    op.drop_index('idx_pharmacy_name', table_name='pharmacies')
    op.drop_index('idx_medical_facility_name', table_name='medical_facilities')
    op.drop_index('idx_geo_indicator_name', table_name='geo_indicators')
    op.drop_index('idx_employee_full_name', table_name='employees')
    op.drop_index('idx_dosage_name', table_name='dosages')
    op.drop_index('idx_dosage_form_name', table_name='dosage_forms')
    op.drop_index('idx_doctor_full_name', table_name='doctors')
    op.drop_index('idx_doctor_company', table_name='doctors')
    op.drop_index('idx_district_name', table_name='districts')
    op.drop_index('idx_country_name', table_name='countries')
    op.drop_index('idx_company_name', table_name='companies')
    op.drop_index('idx_companny_ims_name', table_name='companies')
    op.drop_index('idx_client_category_name', table_name='client_categories')
    op.drop_index('idx_brand_name', table_name='brands')
    op.drop_index('idx_brand_ims_name', table_name='brands')
    op.drop_index('idx_brand_company', table_name='brands')
    # ### end Alembic commands ###
