"""make client_category_id nullable in doctors

Revision ID: 181b4677ed6b
Revises: 32f0728a769c
Create Date: 2026-03-06 19:47:45.818071

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '181b4677ed6b'
down_revision: Union[str, Sequence[str], None] = '32f0728a769c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctors', 'client_category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctors', 'client_category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
