"""empty message

Revision ID: c6068d761f7d
Revises: bbb403440432
Create Date: 2026-02-20 15:59:09.574949

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6068d761f7d"
down_revision: Union[str, Sequence[str], None] = "bbb403440432"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "doctors", "medical_facility_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "doctors", "product_group_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("doctors", "company_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("doctors", "company_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "doctors", "product_group_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "doctors", "medical_facility_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
