"""use_citext_for_name_fields

Revision ID: 8e24f6cf4ffa
Revises: 622bd0cc905a
Create Date: 2026-02-17 11:54:39.993505

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8e24f6cf4ffa"
down_revision: Union[str, Sequence[str], None] = "622bd0cc905a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.alter_column(
        "geo_indicators",
        "name",
        existing_type=sa.VARCHAR(length=256),
        type_=postgresql.CITEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "medical_facilities",
        "name",
        existing_type=sa.VARCHAR(length=256),
        type_=postgresql.CITEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "pharmacies",
        "name",
        existing_type=sa.VARCHAR(length=256),
        type_=postgresql.CITEXT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pharmacies",
        "name",
        existing_type=postgresql.CITEXT(),
        type_=sa.VARCHAR(length=256),
        existing_nullable=False,
    )
    op.alter_column(
        "medical_facilities",
        "name",
        existing_type=postgresql.CITEXT(),
        type_=sa.VARCHAR(length=256),
        existing_nullable=False,
    )
    op.alter_column(
        "geo_indicators",
        "name",
        existing_type=postgresql.CITEXT(),
        type_=sa.VARCHAR(length=256),
        existing_nullable=False,
    )
    op.execute("DROP EXTENSION IF EXISTS citext")
    # ### end Alembic commands ###
