"""remove doctor company-id

Revision ID: 677e947c3a24
Revises: c3b1f6a2d4e9
Create Date: 2026-04-01 12:43:44.816963

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "677e947c3a24"
down_revision: Union[str, Sequence[str], None] = "c3b1f6a2d4e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_district_composite",
        "districts",
        ["name", "region_id", "company_id"],
        unique=False,
    )
    op.drop_index(op.f("idx_doctor_company"), table_name="doctors")
    op.drop_constraint(
        op.f("uq_doctor_full_name_medical_facility_speciality_company"),
        "doctors",
        type_="unique",
    )
    op.drop_constraint(
        op.f("fk_doctors_company_id_companies"), "doctors", type_="foreignkey"
    )
    op.drop_column("doctors", "company_id")
    op.create_index(
        "idx_excel_task_user_status",
        "excel_tasks",
        ["started_by", "status", "is_deleted"],
        unique=False,
    )
    op.create_index(
        "idx_import_logs_created_at",
        "import_logs",
        ["created_at"],
        unique=False,
        postgresql_ops={"created_at": "DESC"},
    )
    op.alter_column(
        "tertiary_sales_and_stock",
        "distributor_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.create_index(
        "idx_user_company_is_active", "users", ["company_id", "is_active"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_user_company_is_active", table_name="users")
    op.alter_column(
        "tertiary_sales_and_stock",
        "distributor_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.drop_index(
        "idx_import_logs_created_at",
        table_name="import_logs",
        postgresql_ops={"created_at": "DESC"},
    )
    op.drop_index("idx_excel_task_user_status", table_name="excel_tasks")
    op.add_column(
        "doctors",
        sa.Column("company_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_doctors_company_id_companies"),
        "doctors",
        "companies",
        ["company_id"],
        ["id"],
    )
    op.drop_constraint(
        "uq_doctor_full_name_medical_facility", "doctors", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_doctor_full_name_medical_facility_speciality_company"),
        "doctors",
        ["full_name", "medical_facility_id", "speciality_id", "company_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(op.f("idx_doctor_company"), "doctors", ["company_id"], unique=False)
    op.drop_index("idx_district_composite", table_name="districts")
    # ### end Alembic commands ###
