"""add excel_tasks enums and soft delete

Revision ID: 82bca18ff88e
Revises: 831beec72a68
Create Date: 2026-02-10 17:23:37.521776

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "82bca18ff88e"
down_revision: Union[str, Sequence[str], None] = "831beec72a68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "excel_tasks",
        sa.Column(
            "task_type",
            sa.Enum("IMPORT", "EXPORT", name="excel_task_type", native_enum=False),
            nullable=False,
        ),
        sa.Column("task_id", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "COMPLETED",
                "FAILED",
                name="excel_task_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("started_by", sa.Integer(), nullable=True),
        sa.Column("file_path", sa.String(length=512), nullable=False),
        sa.Column("error", sa.String(length=500), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "length(error) <= 500", name=op.f("ck_excel_tasks_ck_excel_tasks_error_len")
        ),
        sa.ForeignKeyConstraint(
            ["started_by"],
            ["users.id"],
            name=op.f("fk_excel_tasks_started_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_excel_tasks")),
    )
    op.create_index(
        op.f("ix_excel_tasks_task_id"), "excel_tasks", ["task_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_excel_tasks_task_id"), table_name="excel_tasks")
    op.drop_table("excel_tasks")
    # ### end Alembic commands ###
