"""empty message

Revision ID: aa859b829641
Revises: 62d54bbf69de
Create Date: 2026-03-18 09:00:09.057263

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aa859b829641'
down_revision: Union[str, Sequence[str], None] = '62d54bbf69de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secondary_sales', sa.Column('distributor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_secondary_sales_distributor_id_distributors'), 'secondary_sales', 'distributors', ['distributor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_secondary_sales_distributor_id_distributors'), 'secondary_sales', type_='foreignkey')
    op.drop_column('secondary_sales', 'distributor_id')
    # ### end Alembic commands ###
