"""empty message

Revision ID: 32f0728a769c
Revises: c6068d761f7d
Create Date: 2026-02-22 07:59:21.527116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32f0728a769c'
down_revision: Union[str, Sequence[str], None] = 'c6068d761f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_doctor_full_name_medical_facility_speciality_company', 'doctors', ['full_name', 'medical_facility_id', 'speciality_id', 'company_id'])
    op.drop_constraint(op.f('uq_pharmacy_name_indicator'), 'pharmacies', type_='unique')
    op.create_unique_constraint('uq_pharmacy_name_group_company', 'pharmacies', ['name', 'product_group_id', 'company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_pharmacy_name_group_company', 'pharmacies', type_='unique')
    op.create_unique_constraint(op.f('uq_pharmacy_name_indicator'), 'pharmacies', ['name', 'geo_indicator_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_doctor_full_name_medical_facility_speciality_company', 'doctors', type_='unique')
    # ### end Alembic commands ###
