"""empty message

Revision ID: 916decd3227d
Revises: e0de1a5aa17c
Create Date: 2026-01-28 06:51:17.677637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '916decd3227d'
down_revision: Union[str, Sequence[str], None] = 'e0de1a5aa17c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_full_name_company', 'employees', ['full_name', 'company_id'])
    op.create_unique_constraint('uq_facility_name_indicator', 'medical_facilities', ['name', 'geo_indicator_id'])
    op.create_unique_constraint('uq_pharmacy_name_indicator', 'pharmacies', ['name', 'geo_indicator_id'])
    op.create_unique_constraint('uq_group_name_company', 'product_groups', ['name', 'company_id'])
    op.create_unique_constraint('uq_sku_name_company', 'skus', ['name', 'company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sku_name_company', 'skus', type_='unique')
    op.drop_constraint('uq_group_name_company', 'product_groups', type_='unique')
    op.drop_constraint('uq_pharmacy_name_indicator', 'pharmacies', type_='unique')
    op.drop_constraint('uq_facility_name_indicator', 'medical_facilities', type_='unique')
    op.drop_constraint('uq_full_name_company', 'employees', type_='unique')
    # ### end Alembic commands ###
