"""empty message

Revision ID: 29b145a0adae
Revises: 48726098a1de
Create Date: 2026-04-01 16:17:20.402963

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '29b145a0adae'
down_revision: Union[str, Sequence[str], None] = '48726098a1de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_import_logs_created_at'), table_name='import_logs')
    op.create_index('idx_import_logs_created_at', 'import_logs', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_import_logs_created_at', table_name='import_logs', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_import_logs_created_at'), 'import_logs', [sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###
