"""add export download phase fields to excel_tasks

Revision ID: de0630769647
Revises: 82bca18ff88e
Create Date: 2026-02-10 17:56:15.621238

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de0630769647"
down_revision: Union[str, Sequence[str], None] = "82bca18ff88e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "excel_tasks",
        sa.Column(
            "is_file_download", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "excel_tasks", sa.Column("download_started_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "excel_tasks", sa.Column("download_confirmed_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("excel_tasks", "download_confirmed_at")
    op.drop_column("excel_tasks", "download_started_at")
    op.drop_column("excel_tasks", "is_file_download")
    # ### end Alembic commands ###
