"""empty message

Revision ID: 7097f05a9582
Revises: ef81df17a52b
Create Date: 2026-04-03 03:55:55.240690

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7097f05a9582"
down_revision: Union[str, Sequence[str], None] = "ef81df17a52b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Add speciality_id to doctors (nullable)
    op.add_column("doctors", sa.Column("speciality_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_doctors_speciality_id_specialities"),
        "doctors",
        "specialities",
        ["speciality_id"],
        ["id"],
    )

    # 2. Migrate speciality_id from global_doctors to doctors
    #    Each Doctor record gets the speciality_id from its GlobalDoctor
    op.execute("""
        UPDATE doctors d
        SET speciality_id = gd.speciality_id
        FROM global_doctors gd
        WHERE d.global_doctor_id = gd.id
    """)

    # 3. Deduplicate global_doctors: merge duplicates by (full_name, medical_facility_id)
    #    Keep the one with the lowest id, reassign doctors to it, delete the rest
    op.execute("""
        UPDATE doctors d
        SET global_doctor_id = (
            SELECT MIN(gd2.id)
            FROM global_doctors gd2
            WHERE gd2.full_name = gd.full_name
              AND gd2.medical_facility_id = gd.medical_facility_id
        )
        FROM global_doctors gd
        WHERE d.global_doctor_id = gd.id
          AND EXISTS (
              SELECT 1 FROM global_doctors gd3
              WHERE gd3.full_name = gd.full_name
                AND gd3.medical_facility_id = gd.medical_facility_id
                AND gd3.id != gd.id
          )
    """)

    # Delete duplicate global_doctors
    op.execute("""
        DELETE FROM global_doctors WHERE id IN (
            SELECT gd.id FROM global_doctors gd
            WHERE EXISTS (
                SELECT 1 FROM global_doctors gd2
                WHERE gd2.full_name = gd.full_name
                  AND gd2.medical_facility_id = gd.medical_facility_id
                  AND gd2.id < gd.id
            )
        )
    """)

    # 4. Drop old indexes and constraints
    op.drop_index(op.f("idx_global_doctor_speciality"), table_name="global_doctors")
    op.drop_constraint(
        op.f("uq_global_doctor_unique"), "global_doctors", type_="unique"
    )

    # 5. Create new unique constraint
    op.create_unique_constraint(
        "uq_global_doctor_unique",
        "global_doctors",
        ["full_name", "medical_facility_id"],
    )

    # 6. Drop speciality_id from global_doctors
    op.drop_constraint(
        op.f("fk_global_doctors_speciality_id_specialities"),
        "global_doctors",
        type_="foreignkey",
    )
    op.drop_column("global_doctors", "speciality_id")

    op.drop_index(op.f("idx_import_logs_created_at"), table_name="import_logs")
    op.create_index(
        "idx_import_logs_created_at",
        "import_logs",
        ["created_at"],
        unique=False,
        postgresql_ops={"created_at": "DESC"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_import_logs_created_at",
        table_name="import_logs",
        postgresql_ops={"created_at": "DESC"},
    )
    op.create_index(
        op.f("idx_import_logs_created_at"),
        "import_logs",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.add_column(
        "global_doctors",
        sa.Column("speciality_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_global_doctors_speciality_id_specialities"),
        "global_doctors",
        "specialities",
        ["speciality_id"],
        ["id"],
    )
    op.drop_constraint("uq_global_doctor_unique", "global_doctors", type_="unique")
    op.create_unique_constraint(
        op.f("uq_global_doctor_unique"),
        "global_doctors",
        ["full_name", "medical_facility_id", "speciality_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_global_doctor_speciality"),
        "global_doctors",
        ["speciality_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("fk_doctors_speciality_id_specialities"), "doctors", type_="foreignkey"
    )
    op.drop_column("doctors", "speciality_id")
    # ### end Alembic commands ###
