"""empty message

Revision ID: 30e6bfab72e4
Revises: 29b145a0adae
Create Date: 2026-04-02 10:55:38.308823

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '30e6bfab72e4'
down_revision: Union[str, Sequence[str], None] = '29b145a0adae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_global_doctor_medical_facility', 'global_doctors', ['medical_facility_id'], unique=False)
    op.create_index('idx_global_doctor_speciality', 'global_doctors', ['speciality_id'], unique=False)
    op.drop_index(op.f('idx_import_logs_created_at'), table_name='import_logs')
    op.create_index('idx_import_logs_created_at', 'import_logs', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_primary_sales_sku_year_indicator', 'primary_sales_and_stock', ['sku_id', 'year', 'indicator'], unique=False)
    op.create_index('idx_tertiary_sales_sku_year_indicator', 'tertiary_sales_and_stock', ['sku_id', 'year', 'indicator'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tertiary_sales_sku_year_indicator', table_name='tertiary_sales_and_stock')
    op.drop_index('idx_primary_sales_sku_year_indicator', table_name='primary_sales_and_stock')
    op.drop_index('idx_import_logs_created_at', table_name='import_logs', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_import_logs_created_at'), 'import_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_global_doctor_speciality', table_name='global_doctors')
    op.drop_index('idx_global_doctor_medical_facility', table_name='global_doctors')
    # ### end Alembic commands ###
