"""add_table_name_to_import_log

Revision ID: 0a8370adcc8f
Revises: 8e24f6cf4ffa
Create Date: 2026-02-18 12:39:54.506810

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a8370adcc8f"
down_revision: Union[str, Sequence[str], None] = "8e24f6cf4ffa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "import_logs", sa.Column("target_table_name", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("import_logs", "target_table_name")
    # ### end Alembic commands ###
