from src.db.models import (
    IMS,
    SKU,
    Brand,
    ClientCategory,
    Company,
    Country,
    Distributor,
    District,
    Doctor,
    Dosage,
    DosageForm,
    Employee,
    GeoIndicator,
    GlobalDoctor,
    MedicalFacility,
    Pharmacy,
    Position,
    ProductGroup,
    PromotionType,
    Region,
    Segment,
    Settlement,
    Speciality,
)

REFERENCE_ALIASES = {
    "geography_countries": "geography_countries",
    "geography_settlements": "geography_settlements",
    "geography_regions": "geography_regions",
    "geography_districts": "geography_districts",
    "products_product_groups": "products_product_groups",
    "products_promotion_types": "products_promotion_types",
    "products_brands": "products_brands",
    "products_dosages": "products_dosages",
    "products_dosage_forms": "products_dosage_forms",
    "products_segments": "products_segments",
    "products_skus": "products_skus",
    "employees_positions": "employees_positions",
    "employees_employees": "employees_employees",
    "clients_distributors": "clients_distributors",
    "clients_geo_indicators": "clients_geo_indicators",
    "clients_medical_facilities": "clients_medical_facilities",
    "clients_medical_facility_types": "clients_medical_facility_types",
    "clients_specialities": "clients_specialities",
    "clients_client_categories": "clients_client_categories",
    "clients_doctors": "clients_doctors",
    "clients_pharmacies": "clients_pharmacies",
    "companies_companies": "companies_companies",
    "ims_company_names": "ims_company_names",
    "ims_brand_names": "ims_brand_names",
    "ims_segment_names": "ims_segment_names",
    "ims_dosage_form_names": "ims_dosage_form_names",
}

ALLOWED_REFERENCES = set(REFERENCE_ALIASES.keys())
ALLOWED_SCOPES = {
    "all",
    "clients_clients",
    "sales_primary",
    "sales_secondary",
    "sales_tertiary",
    "visits",
}
ALLOWED_SCOPES.update(ALLOWED_REFERENCES)

REFERENCE_CONFIG = {
    "geography_countries": (Country, Country.name),
    "geography_settlements": (Settlement, Settlement.name),
    "geography_regions": (Region, Region.name),
    "geography_districts": (District, District.name),
    "products_product_groups": (ProductGroup, ProductGroup.name),
    "products_promotion_types": (PromotionType, PromotionType.name),
    "products_brands": (Brand, Brand.name),
    "products_dosages": (Dosage, Dosage.name),
    "products_dosage_forms": (DosageForm, DosageForm.name),
    "products_segments": (Segment, Segment.name),
    "products_skus": (SKU, SKU.name),
    "employees_positions": (Position, Position.name),
    "employees_employees": (Employee, Employee.full_name),
    "clients_distributors": (Distributor, Distributor.name),
    "clients_geo_indicators": (GeoIndicator, GeoIndicator.name),
    "clients_medical_facilities": (MedicalFacility, MedicalFacility.name),
    "clients_medical_facility_types": (MedicalFacility, MedicalFacility.facility_type),
    "clients_specialities": (Speciality, Speciality.name),
    "clients_client_categories": (ClientCategory, ClientCategory.name),
    "clients_doctors": (GlobalDoctor, GlobalDoctor.full_name),
    "clients_pharmacies": (Pharmacy, Pharmacy.name),
    "companies_companies": (Company, Company.name),
}

IMS_REFERENCE_CONFIG: dict[str, any] = {
    "ims_company_names": IMS.company,
    "ims_brand_names": IMS.brand,
    "ims_segment_names": IMS.segment,
    "ims_dosage_form_names": IMS.dosage_form,
}

DEFAULT_COMPANY_FILTER_REFS = {
    "geography_districts",
    "products_product_groups",
    "products_brands",
    "products_skus",
}


FILTER_KEY_TO_MODEL: dict[str, tuple] = {
    "sku_ids": (SKU, SKU.id),
    "brand_ids": (Brand, Brand.id),
    "product_group_ids": (ProductGroup, ProductGroup.id),
    "distributor_ids": (Distributor, Distributor.id),
    "pharmacy_ids": (Pharmacy, Pharmacy.id),
    "doctor_ids": (Doctor, Doctor.id),
    "employee_ids": (Employee, Employee.id),
    "position_ids": (Position, Position.id),
    "region_ids": (Region, Region.id),
    "district_ids": (District, District.id),
    "country_ids": (Country, Country.id),
    "settlement_ids": (Settlement, Settlement.id),
    "medical_facility_ids": (MedicalFacility, MedicalFacility.id),
    "company_ids": (Company, Company.id),
    "segment_ids": (Segment, Segment.id),
    "dosage_ids": (Dosage, Dosage.id),
    "dosage_form_ids": (DosageForm, DosageForm.id),
    "promotion_type_ids": (PromotionType, PromotionType.id),
    "speciality_ids": (Speciality, Speciality.id),
    "client_category_ids": (ClientCategory, ClientCategory.id),
    "geo_indicator_ids": (GeoIndicator, GeoIndicator.id),
}
